BOARD_TAG=uno
F_CPU=16000000UL
MCU=atmega328p
AVR_TOOLS_DIR=/
BOARDS_TXT=/usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
ARDUINO_CORE_PATH=/usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
ARDUINO_VAR_PATH=/usr/share/arduino/hardware/archlinux-arduino/avr/variants
BOOTLOADER_PARENT=/usr/share/arduino/hardware/archlinux-arduino/avr/bootloaders/
include /usr/share/arduino/Arduino.mk
